def get_good_scheme(degree):
    from ._helpers import all_schemes

    if degree <= 50:
        return {
            0: all_schemes["centroid"],
            1: all_schemes["centroid"],
            2: all_schemes["taylor_wingate_bos_1"],
            3: all_schemes["laursen_gellert_04"],
            4: all_schemes["laursen_gellert_05"],
            5: all_schemes["walkington_p5"],
            6: all_schemes["lyness_jespersen_10"],
            7: all_schemes["laursen_gellert_11"],
            8: all_schemes["lyness_jespersen_15"],
            9: all_schemes["lyness_jespersen_18"],
            10: all_schemes["witherden_vincent_10"],
            11: all_schemes["xiao_gimbutas_11"],
            12: all_schemes["xiao_gimbutas_12"],
            13: all_schemes["xiao_gimbutas_13"],
            14: all_schemes["xiao_gimbutas_14"],
            15: all_schemes["witherden_vincent_15"],
            16: all_schemes["xiao_gimbutas_16"],
            17: all_schemes["xiao_gimbutas_17"],
            18: all_schemes["witherden_vincent_18"],
            19: all_schemes["dunavant_19"],
            20: all_schemes["xiao_gimbutas_20"],
            21: all_schemes["xiao_gimbutas_21"],
            22: all_schemes["xiao_gimbutas_22"],
            23: all_schemes["xiao_gimbutas_23"],
            24: all_schemes["xiao_gimbutas_24"],
            25: all_schemes["xiao_gimbutas_25"],
            26: all_schemes["xiao_gimbutas_26"],
            27: all_schemes["xiao_gimbutas_27"],
            28: all_schemes["xiao_gimbutas_28"],
            29: all_schemes["xiao_gimbutas_29"],
            30: all_schemes["xiao_gimbutas_30"],
            31: all_schemes["xiao_gimbutas_31"],
            32: all_schemes["xiao_gimbutas_32"],
            33: all_schemes["xiao_gimbutas_33"],
            34: all_schemes["xiao_gimbutas_34"],
            35: all_schemes["xiao_gimbutas_35"],
            36: all_schemes["xiao_gimbutas_36"],
            37: all_schemes["xiao_gimbutas_37"],
            38: all_schemes["xiao_gimbutas_38"],
            39: all_schemes["xiao_gimbutas_39"],
            40: all_schemes["xiao_gimbutas_40"],
            41: all_schemes["xiao_gimbutas_41"],
            42: all_schemes["xiao_gimbutas_42"],
            43: all_schemes["xiao_gimbutas_43"],
            44: all_schemes["xiao_gimbutas_44"],
            45: all_schemes["xiao_gimbutas_45"],
            46: all_schemes["xiao_gimbutas_46"],
            47: all_schemes["xiao_gimbutas_47"],
            48: all_schemes["xiao_gimbutas_48"],
            49: all_schemes["xiao_gimbutas_49"],
            50: all_schemes["xiao_gimbutas_50"],
        }[degree]()

    # degree > 50
    assert False
    return
