from ._centroid import centroid
from ._dunavant import dunavant_19
from ._taylor_wingate_bos import taylor_wingate_bos_1
from ._xiao_gimbutas import (
    xiao_gimbutas_11,
    xiao_gimbutas_12,
    xiao_gimbutas_13,
    xiao_gimbutas_14,
    xiao_gimbutas_16,
    xiao_gimbutas_17,
    xiao_gimbutas_20,
    xiao_gimbutas_21,
    xiao_gimbutas_22,
    xiao_gimbutas_23,
    xiao_gimbutas_24,
    xiao_gimbutas_25,
    xiao_gimbutas_26,
    xiao_gimbutas_27,
    xiao_gimbutas_28,
    xiao_gimbutas_29,
    xiao_gimbutas_30,
    xiao_gimbutas_31,
    xiao_gimbutas_32,
    xiao_gimbutas_33,
    xiao_gimbutas_34,
    xiao_gimbutas_35,
    xiao_gimbutas_36,
    xiao_gimbutas_37,
    xiao_gimbutas_38,
    xiao_gimbutas_39,
    xiao_gimbutas_40,
    xiao_gimbutas_41,
    xiao_gimbutas_42,
    xiao_gimbutas_43,
    xiao_gimbutas_44,
    xiao_gimbutas_45,
    xiao_gimbutas_46,
    xiao_gimbutas_47,
    xiao_gimbutas_48,
    xiao_gimbutas_49,
    xiao_gimbutas_50,
)
from ._lyness_jespersen import (
    lyness_jespersen_10,
    lyness_jespersen_15,
    lyness_jespersen_18,
)
from ._laursen_gellert import laursen_gellert_04, laursen_gellert_05, laursen_gellert_11
from ._walkington import walkington_p5
from witherden_vincent import witherden_vincent_10, witherden_vincent_15, witherden_vincent_18


def get_good_scheme(degree):
    if degree <= 50:
        return {
            0: centroid,
            1: centroid,
            2: taylor_wingate_bos_1,
            3: laursen_gellert_04,
            4: laursen_gellert_05,
            5: walkington_p5,
            6: lyness_jespersen_10,
            7: laursen_gellert_11,
            8: lyness_jespersen_15,
            9: lyness_jespersen_18,
            10: witherden_vincent_10,
            11: xiao_gimbutas_11,
            12: xiao_gimbutas_12,
            13: xiao_gimbutas_13,
            14: xiao_gimbutas_14,
            15: witherden_vincent_15,
            16: xiao_gimbutas_16,
            17: xiao_gimbutas_17,
            18: witherden_vincent_18,
            19: dunavant_19,
            20: xiao_gimbutas_20,
            21: xiao_gimbutas_21,
            22: xiao_gimbutas_22,
            23: xiao_gimbutas_23,
            24: xiao_gimbutas_24,
            25: xiao_gimbutas_25,
            26: xiao_gimbutas_26,
            27: xiao_gimbutas_27,
            28: xiao_gimbutas_28,
            29: xiao_gimbutas_29,
            30: xiao_gimbutas_30,
            31: xiao_gimbutas_31,
            32: xiao_gimbutas_32,
            33: xiao_gimbutas_33,
            34: xiao_gimbutas_34,
            35: xiao_gimbutas_35,
            36: xiao_gimbutas_36,
            37: xiao_gimbutas_37,
            38: xiao_gimbutas_38,
            39: xiao_gimbutas_39,
            40: xiao_gimbutas_40,
            41: xiao_gimbutas_41,
            42: xiao_gimbutas_42,
            43: xiao_gimbutas_43,
            44: xiao_gimbutas_44,
            45: xiao_gimbutas_45,
            46: xiao_gimbutas_46,
            47: xiao_gimbutas_47,
            48: xiao_gimbutas_48,
            49: xiao_gimbutas_49,
            50: xiao_gimbutas_50,
        }[degree]()

    # degree > 50
    assert False
    return
