def get_good_scheme(degree):
    from ._helpers import schemes

    if degree <= 50:
        return {
            0: schemes["centroid"],
            1: schemes["centroid"],
            2: schemes["hammer_marlowe_stroud_3"],
            3: schemes["strang_fix_cowper_04"],
            4: schemes["williams_shunn_jameson_3"],
            5: schemes["hammer_marlowe_stroud_5"],
            6: schemes["strang_fix_cowper_09"],
            7: schemes["laursen_gellert_11"],
            8: schemes["lyness_jespersen_15"],
            9: schemes["lyness_jespersen_18"],
            10: schemes["dunavant_10"],
            11: schemes["lyness_jespersen_21"],
            12: schemes["dunavant_12"],
            13: schemes["berntsen_espelid_1"],
            14: schemes["dunavant_14"],
            15: schemes["witherden_vincent_15"],
            16: schemes["xiao_gimbutas_16"],
            17: schemes["xiao_gimbutas_17"],
            18: schemes["witherden_vincent_18"],
            19: schemes["dunavant_19"],
            20: schemes["xiao_gimbutas_20"],
            21: schemes["xiao_gimbutas_21"],
            22: schemes["xiao_gimbutas_22"],
            23: schemes["xiao_gimbutas_23"],
            24: schemes["xiao_gimbutas_24"],
            25: schemes["xiao_gimbutas_25"],
            26: schemes["xiao_gimbutas_26"],
            27: schemes["xiao_gimbutas_27"],
            28: schemes["xiao_gimbutas_28"],
            29: schemes["xiao_gimbutas_29"],
            30: schemes["xiao_gimbutas_30"],
            31: schemes["xiao_gimbutas_31"],
            32: schemes["xiao_gimbutas_32"],
            33: schemes["xiao_gimbutas_33"],
            34: schemes["xiao_gimbutas_34"],
            35: schemes["xiao_gimbutas_35"],
            36: schemes["xiao_gimbutas_36"],
            37: schemes["xiao_gimbutas_37"],
            38: schemes["xiao_gimbutas_38"],
            39: schemes["xiao_gimbutas_39"],
            40: schemes["xiao_gimbutas_40"],
            41: schemes["xiao_gimbutas_41"],
            42: schemes["xiao_gimbutas_42"],
            43: schemes["xiao_gimbutas_43"],
            44: schemes["xiao_gimbutas_44"],
            45: schemes["xiao_gimbutas_45"],
            46: schemes["xiao_gimbutas_46"],
            47: schemes["xiao_gimbutas_47"],
            48: schemes["xiao_gimbutas_48"],
            49: schemes["xiao_gimbutas_49"],
            50: schemes["xiao_gimbutas_50"],
        }[degree]()

    # degree > 50
    assert False
    return
