from ._beckers_haegemans import beckers_haegemans_8, beckers_haegemans_9
from ._gatermann import gatermann
from ._hammer_marlowe_stroud import (
    hammer_marlowe_stroud_1,
    hammer_marlowe_stroud_2,
    hammer_marlowe_stroud_3,
)
from ._hammer_stroud import hammer_stroud_2, hammer_stroud_3
from ._jaskowiec_sukumar import (
    jaskowiec_sukumar_02,
    jaskowiec_sukumar_03,
    jaskowiec_sukumar_04,
    jaskowiec_sukumar_05,
    jaskowiec_sukumar_06,
    jaskowiec_sukumar_07,
    jaskowiec_sukumar_08,
    jaskowiec_sukumar_09,
    jaskowiec_sukumar_10,
    jaskowiec_sukumar_11,
    jaskowiec_sukumar_12,
    jaskowiec_sukumar_13,
    jaskowiec_sukumar_14,
    jaskowiec_sukumar_15,
    jaskowiec_sukumar_16,
    jaskowiec_sukumar_17,
    jaskowiec_sukumar_18,
    jaskowiec_sukumar_19a,
    jaskowiec_sukumar_19b,
    jaskowiec_sukumar_20,
)
from ._keast import (
    keast_0,
    keast_1,
    keast_2,
    keast_3,
    keast_4,
    keast_5,
    keast_6,
    keast_7,
    keast_8,
    keast_9,
)
from ._liu_vinokur import (
    liu_vinokur_01,
    liu_vinokur_02,
    liu_vinokur_03,
    liu_vinokur_04,
    liu_vinokur_05,
    liu_vinokur_06,
    liu_vinokur_07,
    liu_vinokur_08,
    liu_vinokur_09,
    liu_vinokur_10,
    liu_vinokur_11,
    liu_vinokur_12,
    liu_vinokur_13,
    liu_vinokur_14,
)
from ._maeztu_sainz import maeztu_sainz
from ._newton_cotes import newton_cotes_closed, newton_cotes_open
from ._shunn_ham import (
    shunn_ham_1,
    shunn_ham_2,
    shunn_ham_3,
    shunn_ham_4,
    shunn_ham_5,
    shunn_ham_6,
)
from ._stroud import stroud_t3_5_1, stroud_t3_7_1
from ._vioreanu_rokhlin import (
    vioreanu_rokhlin_0,
    vioreanu_rokhlin_1,
    vioreanu_rokhlin_2,
    vioreanu_rokhlin_3,
    vioreanu_rokhlin_4,
    vioreanu_rokhlin_5,
    vioreanu_rokhlin_6,
    vioreanu_rokhlin_7,
    vioreanu_rokhlin_8,
    vioreanu_rokhlin_9,
)
from ._walkington import walkington_p5
from ._williams_shunn_jameson import williams_shunn_jameson
from ._witherden_vincent import witherden_vincent_01  # witherden_vincent_04,
from ._witherden_vincent import (
    witherden_vincent_02,
    witherden_vincent_03,
    witherden_vincent_05,
    witherden_vincent_06,
    witherden_vincent_07,
    witherden_vincent_08,
    witherden_vincent_09,
    witherden_vincent_10,
)
from ._xiao_gimbutas import (
    xiao_gimbutas_01,
    xiao_gimbutas_02,
    xiao_gimbutas_03,
    xiao_gimbutas_04,
    xiao_gimbutas_05,
    xiao_gimbutas_06,
    xiao_gimbutas_07,
    xiao_gimbutas_08,
    xiao_gimbutas_09,
    xiao_gimbutas_10,
    xiao_gimbutas_11,
    xiao_gimbutas_12,
    xiao_gimbutas_13,
    xiao_gimbutas_14,
    xiao_gimbutas_15,
)
from ._yu import yu_1, yu_2, yu_3, yu_4, yu_5
from ._zhang_cui_liu import zhang_cui_liu_1, zhang_cui_liu_2

__all__ = [
    "beckers_haegemans_8",
    "beckers_haegemans_9",
    "gatermann",
    "hammer_marlowe_stroud_1",
    "hammer_marlowe_stroud_2",
    "hammer_marlowe_stroud_3",
    "hammer_stroud_2",
    "hammer_stroud_3",
    "jaskowiec_sukumar_02",
    "jaskowiec_sukumar_03",
    "jaskowiec_sukumar_04",
    "jaskowiec_sukumar_05",
    "jaskowiec_sukumar_06",
    "jaskowiec_sukumar_07",
    "jaskowiec_sukumar_08",
    "jaskowiec_sukumar_09",
    "jaskowiec_sukumar_10",
    "jaskowiec_sukumar_11",
    "jaskowiec_sukumar_12",
    "jaskowiec_sukumar_13",
    "jaskowiec_sukumar_14",
    "jaskowiec_sukumar_15",
    "jaskowiec_sukumar_16",
    "jaskowiec_sukumar_17",
    "jaskowiec_sukumar_18",
    "jaskowiec_sukumar_19a",
    "jaskowiec_sukumar_19b",
    "jaskowiec_sukumar_20",
    "keast_0",
    "keast_1",
    "keast_2",
    "keast_3",
    "keast_4",
    "keast_5",
    "keast_6",
    "keast_7",
    "keast_8",
    "keast_9",
    "liu_vinokur_01",
    "liu_vinokur_02",
    "liu_vinokur_03",
    "liu_vinokur_04",
    "liu_vinokur_05",
    "liu_vinokur_06",
    "liu_vinokur_07",
    "liu_vinokur_08",
    "liu_vinokur_09",
    "liu_vinokur_10",
    "liu_vinokur_11",
    "liu_vinokur_12",
    "liu_vinokur_13",
    "liu_vinokur_14",
    "maeztu_sainz",
    "newton_cotes_closed",
    "newton_cotes_open",
    "stroud_t3_5_1",
    "stroud_t3_7_1",
    "shunn_ham_1",
    "shunn_ham_2",
    "shunn_ham_3",
    "shunn_ham_4",
    "shunn_ham_5",
    "shunn_ham_6",
    "vioreanu_rokhlin_0",
    "vioreanu_rokhlin_1",
    "vioreanu_rokhlin_2",
    "vioreanu_rokhlin_3",
    "vioreanu_rokhlin_4",
    "vioreanu_rokhlin_5",
    "vioreanu_rokhlin_6",
    "vioreanu_rokhlin_7",
    "vioreanu_rokhlin_8",
    "vioreanu_rokhlin_9",
    "xiao_gimbutas_01",
    "xiao_gimbutas_02",
    "xiao_gimbutas_03",
    "xiao_gimbutas_04",
    "xiao_gimbutas_05",
    "xiao_gimbutas_06",
    "xiao_gimbutas_07",
    "xiao_gimbutas_08",
    "xiao_gimbutas_09",
    "xiao_gimbutas_10",
    "xiao_gimbutas_11",
    "xiao_gimbutas_12",
    "xiao_gimbutas_13",
    "xiao_gimbutas_14",
    "xiao_gimbutas_15",
    "yu_1",
    "yu_2",
    "yu_3",
    "yu_4",
    "yu_5",
    "zhang_cui_liu_1",
    "zhang_cui_liu_2",
    "walkington_p5",
    "williams_shunn_jameson",
    "witherden_vincent_01",
    "witherden_vincent_02",
    "witherden_vincent_03",
    # "witherden_vincent_04",
    "witherden_vincent_05",
    "witherden_vincent_06",
    "witherden_vincent_07",
    "witherden_vincent_08",
    "witherden_vincent_09",
    "witherden_vincent_10",
]
