from ._albrecht import (
    albrecht_1,
    albrecht_2,
    albrecht_3,
    albrecht_4,
    albrecht_5,
    albrecht_6,
    albrecht_7,
    albrecht_8,
)
from ._albrecht_collatz import albrecht_collatz
from ._cools_haegemans import cools_haegemans_1, cools_haegemans_2, cools_haegemans_3
from ._cools_kim import cools_kim_1, cools_kim_2, cools_kim_3
from ._haegemans_piessens import haegemans_piessens
from ._hammer_stroud import (
    hammer_stroud_11_2,
    hammer_stroud_12_2,
    hammer_stroud_13_2,
    hammer_stroud_17,
    hammer_stroud_18,
    hammer_stroud_19,
    hammer_stroud_20,
    hammer_stroud_21,
)
from ._kim_song import (
    kim_song_1,
    kim_song_2,
    kim_song_3,
    kim_song_4,
    kim_song_5,
    kim_song_6,
    kim_song_7,
    kim_song_8,
    kim_song_9,
    kim_song_10,
    kim_song_11,
    kim_song_12,
    kim_song_13,
    kim_song_14,
    kim_song_15,
)
from ._lether import lether
from ._luo_meng import (
    luo_meng_1,
    luo_meng_2,
    luo_meng_3,
    luo_meng_4,
    luo_meng_5,
    luo_meng_6,
    # luo_meng_7,
)

from ._mysovskih import mysovskih_1, mysovskih_2, mysovskih_3
from ._peirce_1956 import peirce_1956_1, peirce_1956_2, peirce_1956_3
from ._peirce_1957 import peirce_1957
from ._piessens_haegemans import piessens_haegemans
from ._rabinowitz_richter import (
    rabinowitz_richter_1,
    rabinowitz_richter_2,
    rabinowitz_richter_3,
    rabinowitz_richter_4,
    rabinowitz_richter_5,
    rabinowitz_richter_6,
)
from ._radon import radon
from ._stroud import (
    stroud_s2_3_1,
    stroud_s2_3_2,
    stroud_s2_4_1,
    stroud_s2_5_1,
    stroud_s2_5_2,
    stroud_s2_7_1,
    stroud_s2_7_2,
    stroud_s2_9_1,
    stroud_s2_9_2,
    stroud_s2_9_3,
    stroud_s2_9_4,
    stroud_s2_9_5,
    stroud_s2_11_1,
    stroud_s2_11_2,
    stroud_s2_11_3,
    stroud_s2_11_4,
    stroud_s2_13_1,
    stroud_s2_13_2,
    stroud_s2_15_1,
    stroud_s2_15_2,
    stroud_s2_17_1,
)
from ._wissmann_becker import (
    wissmann_becker_6_1,
    wissmann_becker_6_2,
    wissmann_becker_8_1,
)

__all__ = [
    "albrecht_1",
    "albrecht_2",
    "albrecht_3",
    "albrecht_4",
    "albrecht_5",
    "albrecht_6",
    "albrecht_7",
    "albrecht_8",
    "albrecht_collatz",
    "cools_haegemans_1",
    "cools_haegemans_2",
    "cools_haegemans_3",
    "cools_kim_1",
    "cools_kim_2",
    "cools_kim_3",
    "haegemans_piessens",
    "hammer_stroud_11_2",
    "hammer_stroud_12_2",
    "hammer_stroud_13_2",
    "hammer_stroud_17",
    "hammer_stroud_18",
    "hammer_stroud_19",
    "hammer_stroud_20",
    "hammer_stroud_21",
    "kim_song_1",
    "kim_song_2",
    "kim_song_3",
    "kim_song_4",
    "kim_song_5",
    "kim_song_6",
    "kim_song_7",
    "kim_song_8",
    "kim_song_9",
    "kim_song_10",
    "kim_song_11",
    "kim_song_12",
    "kim_song_13",
    "kim_song_14",
    "kim_song_15",
    "lether",
    "luo_meng_1",
    "luo_meng_2",
    "luo_meng_3",
    "luo_meng_4",
    "luo_meng_5",
    "luo_meng_6",
    # "luo_meng_7",
    "mysovskih_1",
    "mysovskih_2",
    "mysovskih_3",
    "peirce_1956_1",
    "peirce_1956_2",
    "peirce_1956_3",
    "peirce_1957",
    "piessens_haegemans",
    "rabinowitz_richter_1",
    "rabinowitz_richter_2",
    "rabinowitz_richter_3",
    "rabinowitz_richter_4",
    "rabinowitz_richter_5",
    "rabinowitz_richter_6",
    "radon",
    "stroud_s2_3_1",
    "stroud_s2_3_2",
    "stroud_s2_4_1",
    "stroud_s2_5_1",
    "stroud_s2_5_2",
    "stroud_s2_7_1",
    "stroud_s2_7_2",
    "stroud_s2_9_1",
    "stroud_s2_9_2",
    "stroud_s2_9_3",
    "stroud_s2_9_4",
    "stroud_s2_9_5",
    "stroud_s2_11_1",
    "stroud_s2_11_2",
    "stroud_s2_11_3",
    "stroud_s2_11_4",
    "stroud_s2_13_1",
    "stroud_s2_13_2",
    "stroud_s2_15_1",
    "stroud_s2_15_2",
    "stroud_s2_17_1",
    "wissmann_becker_6_1",
    "wissmann_becker_6_2",
    "wissmann_becker_8_1",
]
