__author__ = "Nico Schlömer"
__email__ = "nico.schloemer@gmail.com"
__copyright__ = f"Copyright (c) 2016-2020, {__author__} <{__email__}>"
__license__ = "License :: OSI Approved :: MIT License"
__version__ = "0.14.3"
__maintainer__ = "Nico Schlömer"
__status__ = "Development Status :: 4 - Beta"
